//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alici
    {
        public Alici()
        {
            this.Alici_MailGrubu = new HashSet<Alici_MailGrubu>();
        }
    
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string MailAdres { get; set; }
    
        public virtual ICollection<Alici_MailGrubu> Alici_MailGrubu { get; set; }
    }
}
