//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alici_MailGrubu
    {
        public int Id { get; set; }
        public int AliciId { get; set; }
        public int GrupId { get; set; }
    
        public virtual Alici Alici { get; set; }
        public virtual MailGrubu MailGrubu { get; set; }
    }
}
