//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtilacakMail
    {
        public AtilacakMail()
        {
            this.Keywords = new HashSet<Keyword>();
        }
    
        public int Id { get; set; }
        public string MailName { get; set; }
        public string MailPath { get; set; }
    
        public virtual ICollection<Keyword> Keywords { get; set; }
    }
}
