//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAMesajEntities : DbContext
    {
        public DAMesajEntities()
            : base("name=DAMesajEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alici> Alicis { get; set; }
        public virtual DbSet<Alici_MailGrubu> Alici_MailGrubu { get; set; }
        public virtual DbSet<AtilacakMail> AtilacakMails { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<MailGrubu> MailGrubus { get; set; }
        public virtual DbSet<MailGrubu_Keyword> MailGrubu_Keyword { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
