//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailGrubu
    {
        public MailGrubu()
        {
            this.Alici_MailGrubu = new HashSet<Alici_MailGrubu>();
            this.MailGrubu_Keyword = new HashSet<MailGrubu_Keyword>();
        }
    
        public int Id { get; set; }
        public string GrupAd { get; set; }
    
        public virtual ICollection<Alici_MailGrubu> Alici_MailGrubu { get; set; }
        public virtual ICollection<MailGrubu_Keyword> MailGrubu_Keyword { get; set; }
    }
}
